- hosts: {{target}}
  sudo: true
  vars_files:
    - vars.yml

  tasks:
    - name: Install MySQL
      action: apt pkg=$item state=installed
      with_items:
        - mysql-server-core-5.5
        - mysql-client-core-5.5
        - libmysqlclient-dev
        - python-mysqldb
        - mysql-server
        - mysql-client

    - name: Start the MySQL service
      action: service name=mysql state=started

    - name: Remove the test database
      mysql_db: name=test state=absent

    - name: Create deploy user for mysql
      mysql_user: user="subodh" host="%" password=subodh priv=*.*:ALL,GRANT

    - name: Ensure anonymous users are not in the database
      mysql_user: user='' host=$item state=present
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Update mysql root password for all root accounts
      mysql_user: name=root host={{item}} password=subodh
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
