- hosts: "{{target}}"
  tasks:
    - name: Install MySQL
      apt: name= "{{ item }}" state=present
      with_items:
        - mysql_server

    - name: Start the MySQL service
      service: name=mysql state=started

    - name: Remove the test database
      mysql_db: name=test state=absent

    - name: Create deploy user for mysql
      mysql_user: user="subodh" host="%" password=subodh priv=*.*:ALL,GRANT

    - name: Ensure anonymous users are not in the database
      mysql_user: user='' host=$item state=present
      with_items:
        - 127.0.0.1
        - ::1
        - localhost

    - name: Update mysql root password for all root accounts
      mysql_user: name=root host={{item}} password=subodh
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
