---
- name: swapoff
  command: swapoff -a

- name: allocate 3g swapfile
  command: fallocate -l 3G /swapfile

- name: make swap file
  command: mkswap /swapfile

- name: swap on
  command: swapon /swapfile

- name: add the swapfile in fstab to make it permanent after reboot
  lineinfile:
    path: /etc/fstab
    backup: yes
    state: present
    line: '/swapfile swap swap defaults 0 0'

- name: add vim config
  include: vim_editor.yml 
