---
# tasks file for docker
- name: copying docker installation script
  copy:
     src: ../files/get-docker.sh
     dest: ~/scripts/get-docker.sh
     mode: '0744'

- name: running the installation script
  command: ~/scripts/get-docker.sh

- name: update apt-get 
  command: apt-get update

- name: install dependencies
  command: apt-get -y install libffi-dev libssl-dev python3-dev python3 python3-pip

#- name: install docker-compose
#  command: pip3 -v install docker-compose
